---
### 重要 ###
#
#  请注意，如果你想下载皮肤
#  请不要使用来自 https://de.namemc.com 的皮肤
#  它们将在游戏中显示不正确
#
#  使用来自 https://minecraftskins.com 的皮肤.
#
### 重要 ###

# 请在此列出所有皮肤文件名称,无需后缀.
skins:
    - 黑骷髅
    - 傻蛋
    - 火焰
    - 绿箭侠

# 在这里编辑消息.
messages:
    skin-success: "将你的皮肤更改为：{name}."
    skin-reset: "重置了你的皮肤."
    skin-not-exist: "皮肤不存在."
    forms:
        main-form:
            title: "时装库"
            description: "你想做什么？."
            button-1: "皮肤列表"
            button-2: "重置你的皮肤"
        skin-list-form:
            title: "时装库"
            description: "选择你的皮肤."
...